export const EDITOR_STATUS_LOADING = "EDITOR_STATUS_LOADING";
export const EDITOR_STATUS_LOADED = "EDITOR_STATUS_LOADED";
export const EDITOR_STATUS_NEW = "EDITOR_STATUS_NEW";
export const EDITOR_STATUS_UPDATING = "EDITOR_STATUS_UPDATING";
export const EDITOR_STATUS_SYNCED = "EDITOR_STATUS_SYNCED";

export const EDITOR_OPERATION_UPDATE = "EDITOR_OPERATION_UPDATE";
export const EDITOR_OPERATION_CREATE = "EDITOR_OPERATION_CREATE";
export const EDITOR_OPERATION_DELETE = "EDITOR_OPERATION_DELETE";
export const EDITOR_OPERATION_UPLOAD = "EDITOR_OPERATION_UPLOAD";

export const EDITOR_ENTITY_COMPOSITION = "EDITOR_ENTITY_COMPOSITION";
export const EDITOR_ENTITY_MOVEMENT = "EDITOR_ENTITY_MOVEMENT";
export const EDITOR_ENTITY_RECORDING = "EDITOR_ENTITY_RECORDING";
